[build]
  base = "frontend"
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  REACT_APP_API_URL = "https://your-backend-url.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200